import { defineConfig } from "vite";
import { reactRouter } from "@react-router/dev/vite";
import { VitePWA } from "vite-plugin-pwa";
import svgr from "vite-plugin-svgr";
import path from "path";
import prismjs from "vite-plugin-prismjs";

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    reactRouter(),
    svgr(),
    prismjs({
      languages: "all",
      theme: "oneLight",
    }),
    VitePWA({
      registerType: "autoUpdate",
      injectRegister: "auto",

      // This is a stump of the workbox.
      // The actual service worker is generated by the script generate-sw.ts due to an incompatibility between react-router and vite-plugin-pwa.
      workbox: {
        maximumFileSizeToCacheInBytes: 6 * 1024 * 1024,
      },
      manifest: {
        name: "Parallax",
        short_name: "Parallax",
        start_url: process.env.BASE_PATH || "/",
        scope: process.env.BASE_PATH || "/",
        display: "standalone",
        background_color: "#ffffff",
        theme_color: "#ffffff",
        icons: [],
      },
    }),
  ],
  base: process.env.BASE_PATH || "/",
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  css: {
    preprocessorOptions: {
      scss: {
        additionalData: `@use "@/styles/abstracts" as *;`,
      },
    },
  },
});
